name: SonarQube

on: push

jobs:
  sonarQubeTrigger:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: SonarQube Scan
        uses: jankal/sonarqube-action@master
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}

